package com.yfy.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Generated;
import java.util.Date;

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {
    @Id
    private Long id;
    @NotNull
    private String name;
    @NotNull
    private String username;
    @NotNull
    private String idU;
    @NotNull
    private String session_key;
    @NotNull
    private String headPic;
    @NotNull
    private String pwd;
    @NotNull
    private int fxid;
    @NotNull
    private String usertype;
    private java.util.Date date;
    @Generated(hash = 912990687)
    public User(Long id, @NotNull String name, @NotNull String username, @NotNull String idU,
            @NotNull String session_key, @NotNull String headPic, @NotNull String pwd, int fxid,
            @NotNull String usertype, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.username = username;
        this.idU = idU;
        this.session_key = session_key;
        this.headPic = headPic;
        this.pwd = pwd;
        this.fxid = fxid;
        this.usertype = usertype;
        this.date = date;
    }
    @Generated(hash = 586692638)
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getIdU() {
        return this.idU;
    }
    public void setIdU(String idU) {
        this.idU = idU;
    }
    public String getSession_key() {
        return this.session_key;
    }
    public void setSession_key(String session_key) {
        this.session_key = session_key;
    }
    public String getHeadPic() {
        return this.headPic;
    }
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }
    public String getPwd() {
        return this.pwd;
    }
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public int getFxid() {
        return this.fxid;
    }
    public void setFxid(int fxid) {
        this.fxid = fxid;
    }
    public String getUsertype() {
        return this.usertype;
    }
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
    public java.util.Date getDate() {
        return this.date;
    }
    public void setDate(java.util.Date date) {
        this.date = date;
    }



}
